Change processor to prevent errors in python>=3.7
While processing data with bootstrax I noticed errors while processing data with python3.7 or python3.8. Changing this option solves the errors.

The error message is added below for convenience (in python 3.7):
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/concurrent/futures/process.py", line 375, in _queue_management_worker
    thread_wakeup.clear()
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/concurrent/futures/process.py", line 93, in clear
    while self._reader.poll():
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed

or in python 3.8:
	Traceback (most recent call last):
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
	    self.run()
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/threading.py", line 870, in run
	    self._target(*self._args, **self._kwargs)
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/process.py", line 376, in _queue_management_worker
	    thread_wakeup.clear()
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/concurrent/futures/process.py", line 94, in clear
	    self._reader.recv_bytes()
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
	    buf = self._recv_bytes(maxlength)
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
	    buf = self._recv(4)
	  File "/home/xedaq/miniconda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
	 77602 MainThread ThreadedMailboxProcessor Waiting for subprocesses to end
	    chunk = read(handle, remaining)
	OSError: [Errno 9] Bad file descriptor